### PR TITLE
Phone validation : SCOUT-256

### PR DESCRIPTION
**Pull request by ezturner**

### CODE REVIEW

**Comment by ezturner** [comment]
Scout-256

**Comment by mattventura** [comment]
Note the commented-out test case. It tries to turn "office" into the equivalent dialpad numbers 633423

**Comment by mattventura** [comment]
Also, we likely want the error handling behavior cleaned up before merge. Right now it's giving a 500 for failed phone numbers where it should presumably be a 400 like other validation errors.

**Comment by ezturner** [comment]
That's weird, I was trying to catch the exceptions and raise a ValidationError

**Pull request merged**
